name: SuperCrates
main: BajanVlogs\SuperCrates\Main
version: 0.0.3
api: [5.0.0]
load: POSTWORLD
author: BajanVlogs
description: Custom crates that will make your server better

commands:
  givekey:
    description: Give key to player
  setcrate:
    description: Set the location of a crate block
