name: SuperCrates
version: 1.0.0
api: 5.0.0
author: BajanVlogs
main: BajanVlogs\SuperCrates\Main
commands:
  givekey:
    description: "Give a key to a player"
    usage: "/givekey <player> <key id> [amount]"
    permission: "supercrates.givekey"
permissions:
  supercrates.givekey:
    description: "Allows players to give keys to other players"
    default: op
